 language: python
 python:
     - "2.7"
 sudo: false
 cache:
     directories:
         - "~/.platformio"
 install:
     - pip install git+https://github.com/platformio/platformio.git@develop
 script:
     - platformio run
